capture: main.cpp TCPServer.cpp CommunicationMgr.cpp CamSourceV4L2.cpp fec.cpp WifiBcast.cpp udpcomm.cpp
	g++ -o camcap main.cpp TCPServer.cpp CommunicationMgr.cpp CamSourceV4L2.cpp fec.cpp WifiBcast.cpp udpcomm.cpp -lpthread -lpcap -std=c++17

clean:
	rm camcap
